Repository OPGG-HACKTHON/MusicWard-Server, pull requests merged in 2021-09, with the labels that each got.

#198 🔀 :: (#196) ranking 500 에러 이슈
  src/main/java/io/github/opgg/music_ward_server/dto/ranking/response/RankingMainResponse.java
Labels: 버그, chore

#197 🔀 :: (#190) 플레이리스트명 검색 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: 기능 추가

#200 🔀 :: (#199) Page 관련 dto 수정
  src/main/java/io/github/opgg/music_ward_server/dto/page/request/PageMainRequest.java
Labels: chore

#204 🔀 :: (#203) 챔피언 리스트 조회 정렬 변경
  src/main/java/io/github/opgg/music_ward_server/controller/ChampionController.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionService.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: 기능 추가

#201 🔀 :: (#191) 태그명 검색 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/request/PageMainRequest.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/TagRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/UnsupportedSortTypeException.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: 기능 추가

#206 🔀 :: (#205) 챔피언 리스트 조회 기능확장
  src/main/java/io/github/opgg/music_ward_server/controller/ChampionController.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionService.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: 기능 추가

#207 🔀 :: (#202) search 조회 부분 수정
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/Tag.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/TagRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: 기능 추가, chore

#208 🔀 :: (#114) 코드 정리
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: chore

#212 🔀 :: (#211) READMD 초안 작성
  README.md
Labels: DOCS

#214 🔀 :: (#213) 자신이 와딩한 플레이리스트 목록 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/request/PageMainRequest.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/Ward.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 기능 추가, chore

#216 🔀 :: (#215) playlist 검색 조건 추가
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: chore

#218 🔀 :: (#217) 챔피언정보 검색 에러 결과수정
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: chore

#220 🔀 :: (#219) 엔티티 테스트 점검 및 수정
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/report/Report.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/Tag.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/Token.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/Track.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/Ward.java
  src/test/java/io/github/opgg/music_ward_server/entity/champion/ChampionTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
Labels: 테스트 추가

#225 🔀 :: (#224) options 허용
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: chore

#228 🔀 :: (#227) 자신의 플레이리스트 목록 조회 url 수정
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: chore

#222 🔀 :: (#221) 플레이리스트 검색 조건 수정
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: chore

#226 🔀 :: (#223) 랭킹에 곡 개수 정보 추가 및 챔피언 sub title 수정
  src/main/java/io/github/opgg/music_ward_server/dto/ranking/response/RankingMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/service/ranking/RankingServiceImpl.java
Labels: chore

#230 🔀 :: (#229) 챔피언 상세조회 보이스음성 URL추가
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionDetailDTO.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
  src/main/resources/application.properties
Labels: 기능 추가

#232 🔀 :: (#231) 통합 테스트 환경 설정
  .gitignore
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
  src/test/java/io/github/opgg/music_ward_server/BaseIntegrationTest.java
  src/test/java/io/github/opgg/music_ward_server/MusicWardServerApplicationTest.java
  src/test/resources/application-test.properties
Labels: 기능 추가

#236 🔀 :: (#233) 소환사명 검색 즐겨하는 챔피언 한글로 표시
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: chore

#238 🔀 :: (#237) champion 관련 통합 테스트 작성
  .gitignore
  src/main/java/io/github/opgg/music_ward_server/controller/ChampionController.java
  src/test/java/io/github/opgg/music_ward_server/BaseIntegrationTest.java
  src/test/java/io/github/opgg/music_ward_server/controller/ChampionControllerTest.java
  src/test/resources/application-test.properties
Labels: 테스트 추가

#242 🔀 :: (#241) CORS 해결
  src/main/java/io/github/opgg/music_ward_server/config/WebConfig.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/FilterConfigure.java
Labels: 버그

#243 🔀 :: (#241) CORS 에러 해결
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: 버그

#245 🔀 :: (#244) CORS 관련 url 설정
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: 버그

#247 🔀 :: (#246) cors header contains multiple values 발생
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: 버그

#249 🔀 :: (#248) addHeader -> setHeader 변경 및 * 처리
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: 버그

#250 🔀 :: (#239) 플레이리스트 관련 통합 테스트 추가
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/utils/security/SecurityUtil.java
  src/test/java/io/github/opgg/music_ward_server/controller/ChampionControllerTest.java
  src/test/java/io/github/opgg/music_ward_server/controller/PlaylistControllerTest.java
Labels: 테스트 추가

#252 🔀 :: (#251) readme 수정
  README.md
Labels: DOCS, chore

#256 🔀 :: (#255) SecurityUtil 수정
  src/main/java/io/github/opgg/music_ward_server/utils/security/SecurityUtil.java
Labels: 버그

#254 🔀 :: (#253) 유저 컨트롤러 테스트
  src/test/java/io/github/opgg/music_ward_server/controller/UserControllerTest.java
Labels: 테스트 추가

#258 🔀 :: (#257) token이 필요한 플레이리스트 통합 테스트 추가
  src/test/java/io/github/opgg/music_ward_server/MusicWardServerApplicationTest.java
  src/test/java/io/github/opgg/music_ward_server/controller/PlaylistControllerTest.java
  src/test/resources/application-test.properties
  src/test/resources/data.sql
Labels: 테스트 추가

#260 🔀 :: (#259)소환사명 검색 에러메세지 추가
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/MatchNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/exception/SummonerNameNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
Labels: 기능 추가

#265 🔀 :: (#263) 플레이리스트 검색 관련 통합 테스트 작성
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/test/java/io/github/opgg/music_ward_server/BaseIntegrationTest.java
  src/test/java/io/github/opgg/music_ward_server/controller/SearchControllerTest.java
Labels: 테스트 추가

#266 🔀 :: (#264) 댓글 관련 테스트
  src/main/java/io/github/opgg/music_ward_server/controller/CommentController.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/CommentRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/EditCommentRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/RemoveCommentRequest.java
  src/test/java/io/github/opgg/music_ward_server/controller/CommentControllerTest.java
  src/test/java/io/github/opgg/music_ward_server/controller/UserControllerTest.java
Labels: 테스트 추가

#269 🔀 :: (#268) 플레이리스트 관련 코드 정리
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/request/PlaylistSaveRequest.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/Track.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/Ward.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/NotYourPlaylistException.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: chore

#271 🔀 :: (#270) PATCH http 메소드 허용
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: chore

#273 🔀 :: (#272) 플레이리스트 동기화 및 삭제 기능 수정
  src/main/java/io/github/opgg/music_ward_server/entity/comment/CommentRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 버그

#275 🔀 :: (#274) PUT http 메소드 허용
  src/main/java/io/github/opgg/music_ward_server/security/jwt/CorsFilter.java
Labels: chore

#277 🔀 :: (#276) README 업데이트
  README.md
Labels: chore

#279 🔀 :: (#278) 스포티파이 로그인 500
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/AlreadyRegisteredEmailException.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그

#281 🔀 :: (#280) 회원탈퇴 수정
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/test/java/io/github/opgg/music_ward_server/controller/PlaylistControllerTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
  src/test/resources/data.sql
Labels: 버그

#283 🔀 :: (#282) 유튜브 플레이리스트 external url 수정
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistsResponse.java
Labels: chore

#285 🔀 :: (#284) 플레이리스트 삭제 부분 수정
  src/main/java/io/github/opgg/music_ward_server/entity/report/ReportRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 버그

#291 🔀 :: (#289) Google RefreshToken
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그

#293 🔀 :: (#286) 토큰 삭제 롤백
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그

#295 🔀 :: (#292) youtube 플레이리스트 조회 개수 조정
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleApiClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistsResponse.java
Labels: chore

#296 🔀 :: (#294) OAuth RefreshToken이 Null일 때 저장
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그

#290 🔀 :: (#287) 스포티파이 없는 image 조회 시 nullPointerException
  src/main/java/io/github/opgg/music_ward_server/dto/ranking/response/RankingMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyPlaylistResponse.java
Labels: 버그

#298 🔀 :: (#297) spotify 이미지 부분 수정
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyPlaylistResponse.java
Labels: 버그

#299 🔀 :: (#267) 테스트 레디스 설정
  build.gradle
  src/test/java/io/github/opgg/music_ward_server/config/RedisConfiguration.java
  src/test/java/io/github/opgg/music_ward_server/config/TestRedisConfig.java
  src/test/resources/application-test.properties
Labels: 프로젝트 설정

#301 🔀 :: (#300) 유튜브 이미지 관련 수정
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistResponse.java
Labels: 버그

#303 🔀 :: (#302) readme github repository 링크 추가
  README.md
Labels: DOCS
