Repository OPGG-HACKTHON/MusicWard-Server, pull requests merged in 2021-08, with the labels that each got.

#2 엔티티 클래스 정의
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/config/JpaConfig.java
  src/main/java/io/github/opgg/music_ward_server/entity/BaseEntity.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/CommentRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/ServiceType.java
  src/main/java/io/github/opgg/music_ward_server/entity/report/Report.java
  src/main/java/io/github/opgg/music_ward_server/entity/report/ReportRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/song/Song.java
  src/main/java/io/github/opgg/music_ward_server/entity/song/SongRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/Tag.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/TagRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/UserRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/Ward.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/WardRepository.java
  src/test/java/io/github/opgg/music_ward_server/MusicWardServerApplicationTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/champion/ChampionTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/song/SongTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
Labels: 기능 추가, 테스트 추가

#4 🔀 :: properties에 DB정보 추가
  src/main/resources/application.properties
Labels: 프로젝트 설정

#6 🔀 :: Entity 이름 변경
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/report/Report.java
  src/main/java/io/github/opgg/music_ward_server/entity/song/SongRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/Tag.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/Track.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/TrackRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/Ward.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
Labels: chore

#8 🔀 :: (#7) 유저 엔티티 상세
  src/main/java/io/github/opgg/music_ward_server/entity/user/Role.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
Labels: chore

#10 🔀 :: (#9) Security 세팅
  src/main/java/io/github/opgg/music_ward_server/config/WebConfig.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: 프로젝트 설정

#12 🔀 :: (#11) 토큰 엔티티 구현
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/entity/token/Token.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/TokenRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/Type.java
Labels: 프로젝트 설정

#19 🔀 :: (#16) UserDetailsService 구현
  src/main/java/io/github/opgg/music_ward_server/security/jwt/auth/AuthDetailsService.java
Labels: chore, 프로젝트 설정

#18 🔀 :: (#15) DB 설정
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/config/RedisConfig.java
  src/main/resources/application.properties
Labels: 프로젝트 설정

#25 🔀 :: (#24) CD 설정
  Dockerfile
  build.gradle
Labels: 프로젝트 설정

#26 🔀 :: CD 설정..
  .github/workflows/release.yml
Labels: 프로젝트 설정

#33 🔀 :: (#30) CORS 메소드 설정
  src/main/java/io/github/opgg/music_ward_server/config/WebConfig.java
Labels: 프로젝트 설정

#35 🔀 :: (#34) 도커 이미지 태그 변경
  .github/workflows/release.yml
Labels: 프로젝트 설정

#37 🔀 :: (#31) Jwt 토큰 필터 구현
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/ExpiredAccessTokenException.java
  src/main/java/io/github/opgg/music_ward_server/exception/ExpiredRefreshTokenException.java
  src/main/java/io/github/opgg/music_ward_server/exception/InvalidTokenException.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/JwtTokenFilter.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#39 🔀 :: (#32) 에러 핸들링 필터
  src/main/java/io/github/opgg/music_ward_server/error/ErrorResponse.java
  src/main/java/io/github/opgg/music_ward_server/error/ExceptionHandlerFilter.java
  src/main/java/io/github/opgg/music_ward_server/error/GlobalExceptionHandler.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/FilterConfigure.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/JwtTokenProvider.java
Labels: 프로젝트 설정

#40 🔀 :: (#23) 로그 설정
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/security/logging/LogWriter.java
  src/main/java/io/github/opgg/music_ward_server/security/logging/RequestLogger.java
  src/main/java/io/github/opgg/music_ward_server/security/logging/RequestWrapper.java
  src/main/resources/application.properties
Labels: 프로젝트 설정

#43 🔀 :: (#42) 유저 컬럼 변경사항 적용
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/JwtTokenProvider.java
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
Labels: chore, 프로젝트 설정

#44 🔀 :: (#41) 구글 로그인 링크
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/resources/application.properties
Labels: 기능 추가

#46 🔀 :: (#45) 로그 ip 오류해결
  src/main/java/io/github/opgg/music_ward_server/security/logging/RequestLogger.java
Labels: chore, 프로젝트 설정

#48 🔀 :: (#47) Spring Cloud OpenFeign 설정
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/utils/api/FeignClientErrorDecoder.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/FeignConfiguration.java
Labels: 프로젝트 설정

#52 🔀 :: (#50) 예외처리 개선
  src/main/java/io/github/opgg/music_ward_server/error/GlobalExceptionHandler.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/JwtTokenFilter.java
Labels: 버그, chore, 리팩토링

#53 🔀 :: (#49) 구글 로그인 Api
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/GoogleLinkResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/TokenResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/UserRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/EmailTooLongException.java
  src/main/java/io/github/opgg/music_ward_server/exception/RequestFailToOtherServerException.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/FeignClientErrorDecoder.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleAuthClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleInfoClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/CodeRequest.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleEmailResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleTokenResponse.java
  src/main/resources/application.properties
Labels: 기능 추가

#56 🔀 :: (#55) google OAuth 2.0 redirect uri 관련 수정
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: 버그, chore

#58 🔀 :: (#57) SecurityUtil 구현
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/CredentialsNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/utils/security/SecurityUtil.java
Labels: 기능 추가

#62 🔀 :: (#61) redis 관련 query creation 오류 해결
  src/main/java/io/github/opgg/music_ward_server/entity/token/Token.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/TokenRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그, chore

#64 🔀 :: (#63) google refresh token을 활용한 access token 조회 구현
  src/main/java/io/github/opgg/music_ward_server/entity/token/Token.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleAuthClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleAccessTokenRequest.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleAccessTokenResponse.java
Labels: 기능 추가

#66 🔀 :: (#54) 등록하지 않은 플레이리스트 목록 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/controller/response/CommonResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/NonPlaylistsResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Provider.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/EmptyRefreshTokenException.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleApiClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleInfoClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleAccessTokenResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleTokenResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistsResponse.java
  src/main/resources/application.properties
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
Labels: 기능 추가

#72 🔀 :: (#59) 챔피언관련 조회 API 구현 기능 추가
  src/main/java/io/github/opgg/music_ward_server/controller/ChampionController.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionDataDTO.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionDetailDTO.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionListDTO.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionListResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/ChampionNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionService.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: 기능 추가, chore

#71 🔀 :: (#69) Google Info Client api url 변경
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/GoogleInfoClient.java
Labels: chore

#70 🔀 :: (#67) 토큰 구조 변경
  src/main/java/io/github/opgg/music_ward_server/entity/token/Token.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/TokenRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: chore

#78 🔀 :: (#77) 스포티파이 로그인 링크 Api
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/LinkResponse.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/resources/application.properties
Labels: 기능 추가

#76 🔀 :: (#75) validation 예외 handle 및 error response 수정
  src/main/java/io/github/opgg/music_ward_server/error/ErrorResponse.java
  src/main/java/io/github/opgg/music_ward_server/error/GlobalExceptionHandler.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
Labels: 기능 추가

#80 🔀 :: (#79) google refresh token 관련 버그 해결
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그, chore

#81 🔀 :: (#73) 스포티파이 로그인 Api
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/UserRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleApiClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleAuthClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleInfoClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/spotify/SpotifyAuthClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/spotify/SpotifyInfoClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleCodeRequest.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyCodeRequest.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyEmailResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyTokenResponse.java
Labels: 기능 추가

#85 🔀 :: (#84) Controller에서 반환형 CommonResponse로 수정
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
Labels: chore

#82 🔀 :: (#74) 플레이리스트 등록 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/request/PlaylistSaveRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/NonPlaylistsResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/PlaylistMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/track/request/TrackSaveRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/track/response/TrackMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/UserMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Image.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/Track.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/TrackRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleApiClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleAccessTokenRequest.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistsResponse.java
  src/test/java/io/github/opgg/music_ward_server/dto/playlist/PlaylistSaveRequestTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/comment/CommentTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/report/ReportTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/tag/TagTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/track/TrackTest.java
  src/test/java/io/github/opgg/music_ward_server/entity/ward/WardTest.java
Labels: 기능 추가, chore

#86 🔀 :: (#83) 플레이리스트 목록 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/PlaylistMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/CommentRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/tag/TagRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/track/TrackRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/WardRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#90 🔀 :: (#87) 플레이리스트 단 건 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/response/CommentMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/PlaylistMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/PlaylistNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 기능 추가

#95 🔀 :: (#94) ChampionController 상태코드 및 다른 Controller와 양식통일
  src/main/java/io/github/opgg/music_ward_server/controller/ChampionController.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionDataDTO.java
Labels: chore

#91 🔀 :: (#89) playlist controller API별 상태코드 수정
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
Labels: chore

#99 🔀 :: (#93) 특정 user가 등록한 플레이리스트 목록 조회 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 기능 추가

#100 🔀 :: (#92) 플레이리스트 삭제 및 조회수 증가 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/WardRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 기능 추가

#104 🔀 :: (#103) 플레이리스트 요청과 응답 시 snake case로 변경
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/response/CommentMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/request/PlaylistSaveRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/request/PlaylistUpdateRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/NonPlaylistsResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/PlaylistMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/track/response/TrackMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/UserMainResponse.java
  src/test/java/io/github/opgg/music_ward_server/dto/playlist/request/PlaylistUpdateRequestTest.java
Labels: chore

#102 🔀 :: (#101) 챔피언 이름 별 플레이리스트 목록 조회를 위한 기능 개선
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/controller/response/PageResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/request/PageMainRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/response/PageInfoResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistService.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 기능 추가, chore

#107 🔀 :: (#106) UserController OAuth route 수정
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: chore

#112 🔀 :: (#97) UserController 반환타입 변경
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
Labels: chore

#117 🔀 :: (#115) OAuth에서 code부분 URIDecode로 처리
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: chore

#108 🔀 :: (#105) 플레이리스트를 보유한 user만 해당 플레이리스트를 조작할 수 있도록 제한
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/playlist/PlaylistServiceImpl.java
Labels: 버그, chore

#110 🔀 :: (#109) playlist 관련 dto 전반적인 점검 및 필드 추가
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/response/CommentMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/response/PageInfoResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/NonPlaylistsResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/playlist/response/PlaylistMainResponse.java
Labels: chore

#119 🔀 :: (#118) 회원 탈퇴 Api
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/WardRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#121 🔀 :: (#120) 토큰 재발급 Api
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/request/RefreshTokenRequest.java
  src/main/java/io/github/opgg/music_ward_server/entity/token/TokenRepository.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#125 🔀 :: (#124) Spotify Token 저장 버그
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 버그, chore

#151 🔀 :: (#150) 와드 제거 Api
  src/main/java/io/github/opgg/music_ward_server/controller/WardController.java
  src/main/java/io/github/opgg/music_ward_server/dto/ward/request/RemoveWardRequest.java
  src/main/java/io/github/opgg/music_ward_server/entity/ward/WardRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/WardNotFoundException.java
  src/main/java/io/github/opgg/music_ward_server/service/ward/WardService.java
  src/main/java/io/github/opgg/music_ward_server/service/ward/WardServiceImpl.java
Labels: 기능 추가

#156 🔀 :: (#155) 챔피언 별 랭킹 목록 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/RankingController.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionRankingResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/entity/comment/Comment.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/Playlist.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionService.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: 기능 추가

#152 🔀 :: (#141) Dto에 Validator 적용
  src/main/java/io/github/opgg/music_ward_server/controller/CommentController.java
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/CommentRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/EditCommentRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/comment/request/RemoveCommentRequest.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/request/RefreshTokenRequest.java
  src/main/java/io/github/opgg/music_ward_server/service/comment/CommentServiceImpl.java
Labels: chore

#165 🔀 :: (#162) spotify 에서 조회되는 데이터가 없는 경우 던지는 IndexOutOfBoundsException
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/spotify/SpotifyPlaylistsResponse.java
Labels: 버그, chore

#168 🔀 :: (#167) champion findAll 조회 부분 수정
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionListDTO.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/Champion.java
  src/main/java/io/github/opgg/music_ward_server/entity/champion/ChampionRepository.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
Labels: 버그, chore

#164 🔀 :: (#163) RequestLogger Filter 위치 변경
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/security/jwt/FilterConfigure.java
Labels: chore

#166 🔀 :: (#157) Swagger 설정
  build.gradle
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
Labels: 프로젝트 설정

#174 🔀 :: (#173) nickname으로 통일
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/UserInfoResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/response/UserMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
Labels: chore

#170 🔀 :: (#169) youtube 플레이리스트 조회 null 체크
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/YoutubePlaylistsResponse.java
Labels: 버그, chore

#175 🔀 :: (#158) 닉네임 변경
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/dto/user/request/ModifyNicknameRequest.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#176 🔀 :: (#159) 회원가입 시 name 입력
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/google/GoogleInfoClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/google/GoogleInfoResponse.java
Labels: chore

#177 🔀 :: (#172) properties에서 환경변수 값 받아오는 부분 수정
  src/main/java/io/github/opgg/music_ward_server/config/PropertiesConfig.java
  src/main/java/io/github/opgg/music_ward_server/config/properties/GoogleProperties.java
  src/main/java/io/github/opgg/music_ward_server/config/properties/SpotifyProperties.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: chore

#179 🔀 :: (#178) nickname 수정 controller에 추가
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
Labels: 버그

#171 🔀 :: (#96) Riot 소환사명 검색 API 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/dto/search/response/SearchSummonerResponse.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServicempl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/riot/RiotMatchClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/riot/RiotSummonerClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/riot/RiotMatchDetailResponse.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/dto/riot/RiotSummonerResponse.java
  src/main/resources/application.properties
Labels: 기능 추가, chore

#181 🔀 :: (#180) 플레이리스트 별 랭킹 목록 조회 구현
  src/main/java/io/github/opgg/music_ward_server/controller/RankingController.java
  src/main/java/io/github/opgg/music_ward_server/controller/response/PageResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/champion/response/ChampionRankingResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/page/response/PageInfoResponse.java
  src/main/java/io/github/opgg/music_ward_server/dto/ranking/response/RankingMainResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/UnsupportedRankingTypeException.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionService.java
  src/main/java/io/github/opgg/music_ward_server/service/champion/ChampionServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/ranking/RankingService.java
  src/main/java/io/github/opgg/music_ward_server/service/ranking/RankingServiceImpl.java
Labels: 기능 추가

#182 🔀 :: (#160) Spotify 로그인부분 개선
  src/main/java/io/github/opgg/music_ward_server/controller/UserController.java
  src/main/java/io/github/opgg/music_ward_server/security/SecurityConfig.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserService.java
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#183 🔀 :: (#161) 닉네임 자동 입력
  src/main/java/io/github/opgg/music_ward_server/service/user/UserServiceImpl.java
Labels: 기능 추가

#185 🔀 :: (#184) spring cache 적용
  src/main/java/io/github/opgg/music_ward_server/config/CacheConfig.java
  src/main/resources/application.properties
Labels: 기능 추가

#187 🔀 :: (#186) ranking cache 적용
  src/main/java/io/github/opgg/music_ward_server/service/ranking/RankingServiceImpl.java
Labels: 기능 추가

#195 🔀 :: (#194) CORS 허용
  src/main/java/io/github/opgg/music_ward_server/config/WebConfig.java
Labels: chore

#193 🔀 :: (#192) 유저 엔티티 개선
  src/main/java/io/github/opgg/music_ward_server/entity/user/User.java
  src/test/java/io/github/opgg/music_ward_server/entity/user/UserTest.java
Labels: chore

#189 🔀 :: (#188) 챔피언명 검색 기능 구현
  src/main/java/io/github/opgg/music_ward_server/controller/PlaylistController.java
  src/main/java/io/github/opgg/music_ward_server/controller/SearchController.java
  src/main/java/io/github/opgg/music_ward_server/dto/search/response/SearchSummonerResponse.java
  src/main/java/io/github/opgg/music_ward_server/entity/playlist/PlaylistRepository.java
  src/main/java/io/github/opgg/music_ward_server/error/exception/ErrorCode.java
  src/main/java/io/github/opgg/music_ward_server/exception/UnsupportedSearchTypeException.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchService.java
  src/main/java/io/github/opgg/music_ward_server/service/search/SearchServiceImpl.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/riot/RiotMatchClient.java
  src/main/java/io/github/opgg/music_ward_server/utils/api/client/riot/RiotSummonerClient.java
Labels: 기능 추가
